-- ==========================================================
-- neXsv | Engagement de publicaciones
-- Guardados por miembro + eventos de compartir
-- ==========================================================

create table if not exists public.community_publication_saves (
    publication_id uuid not null references public.community_publications(id) on delete cascade,
    saver_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (publication_id, saver_id)
);

create index if not exists idx_community_publication_saves_publication
    on public.community_publication_saves(publication_id);

alter table public.community_publication_saves enable row level security;

create table if not exists public.community_publication_shares (
    id bigint generated by default as identity primary key,
    publication_id uuid not null references public.community_publications(id) on delete cascade,
    sharer_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

create index if not exists idx_community_publication_shares_publication
    on public.community_publication_shares(publication_id);

alter table public.community_publication_shares enable row level security;

-- El cliente usa funciones seguras; no se expone acceso directo a las tablas.
revoke all on public.community_publication_saves from anon, authenticated;
revoke all on public.community_publication_shares from anon, authenticated;

create or replace function public.toggle_community_publication_save(p_publication_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user uuid := auth.uid();
    v_saved boolean;
begin
    if v_user is null then
        raise exception 'AUTH_REQUIRED';
    end if;

    if not exists (
        select 1 from public.community_publications p
        where p.id = p_publication_id and p.status = 'PUBLICADA'
    ) then
        raise exception 'PUBLICATION_NOT_FOUND';
    end if;

    if exists (
        select 1 from public.community_publication_saves s
        where s.publication_id = p_publication_id and s.saver_id = v_user
    ) then
        delete from public.community_publication_saves
        where publication_id = p_publication_id and saver_id = v_user;
        v_saved := false;
    else
        insert into public.community_publication_saves (publication_id, saver_id)
        values (p_publication_id, v_user)
        on conflict (publication_id, saver_id) do nothing;
        v_saved := true;
    end if;

    return v_saved;
end;
$$;

grant execute on function public.toggle_community_publication_save(uuid) to authenticated;

create or replace function public.get_my_community_publication_save_state(p_publication_ids uuid[])
returns table (
    publication_id uuid,
    saved boolean
)
language sql
security definer
set search_path = public
as $$
    select
        ids.id,
        exists (
            select 1
            from public.community_publication_saves s
            where s.publication_id = ids.id
              and s.saver_id = auth.uid()
        ) as saved
    from unnest(coalesce(p_publication_ids, '{}'::uuid[])) as ids(id)
    where auth.uid() is not null;
$$;

grant execute on function public.get_my_community_publication_save_state(uuid[]) to authenticated;

create or replace function public.record_community_publication_share(p_publication_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if auth.uid() is null then
        raise exception 'AUTH_REQUIRED';
    end if;

    insert into public.community_publication_shares (publication_id, sharer_id)
    select p_publication_id, auth.uid()
    where exists (
        select 1 from public.community_publications p
        where p.id = p_publication_id and p.status = 'PUBLICADA'
    );
end;
$$;

grant execute on function public.record_community_publication_share(uuid) to authenticated;

create or replace function public.get_my_community_publication_engagement_metrics()
returns table (
    publication_id uuid,
    shares bigint,
    saves bigint
)
language sql
security definer
set search_path = public
as $$
    select
        p.id,
        (select count(*) from public.community_publication_shares s where s.publication_id = p.id),
        (select count(*) from public.community_publication_saves s where s.publication_id = p.id)
    from public.community_publications p
    where p.author_id = auth.uid()
      and p.status = 'PUBLICADA';
$$;

grant execute on function public.get_my_community_publication_engagement_metrics() to authenticated;
